# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provincia', '0001_initial'),
        ('Canton', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Provincia.provincia'),
        ),
    ]
