# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provincia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.TextField(max_length=50)),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Provincia.provincia')),
            ],
        ),
    ]
