# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=70)),
                ('fecha', models.DateField()),
                ('tipos', models.CharField(max_length=50)),
            ],
        ),
    ]
