# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Palabra_clave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra_clave',
            name='investigador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador'),
        ),
    ]
