# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zona', '0002_auto_20171126_1613'),
        ('Provincia', '0002_auto_20171126_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zona.zona'),
        ),
    ]
