# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facultad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Director', models.CharField(max_length=30)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facultad.facultad')),
            ],
        ),
    ]
