# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0003_auto_20171204_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Nombre',
            field=models.CharField(max_length=300),
        ),
    ]
