# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Revista', '0023_auto_20171201_1556'),
        ('Ponencia', '0004_auto_20171201_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='revista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Revista.revista'),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
