# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ponencia', '0015_auto_20171203_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponencia',
            name='Certificado',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='Datos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='Tipo_Publicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='Titulo_Publicacion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
