# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Zona', '0001_initial'),
        ('Pais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Rector', models.CharField(max_length=20)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.pais')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zona.zona')),
            ],
        ),
    ]
