# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0002_auto_20171126_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
