# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0050_auto_20171209_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigaciones',
            name='PalabrasClave',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investigaciones',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
