# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canton', '0002_canton_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='Nombre',
            field=models.CharField(max_length=20),
        ),
    ]
