# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revista', '0019_auto_20171129_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
