# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revista', '0026_auto_20171201_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='Numero_Revista',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revista',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
