# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revista', '0029_auto_20171203_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='ISSN',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='revista',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
