# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investigador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='intereses_formativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tematica_Interes', models.CharField(max_length=30)),
                ('Descripcion', models.TextField(verbose_name=70)),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador')),
            ],
        ),
    ]
