# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Intereses_Formativos', '0051_auto_20171209_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='intereses_formativos',
            name='PalabrasClave',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intereses_formativos',
            name='investigador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador'),
        ),
    ]
