# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigador', '0002_auto_20171126_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigador',
            name='id',
        ),
        migrations.AlterField(
            model_name='investigador',
            name='cedula',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
