# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigador', '0003_auto_20171129_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='Telefono',
            field=models.CharField(max_length=12),
        ),
    ]
