# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigador', '0004_auto_20171129_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='Foto',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
