# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigador', '0006_auto_20171209_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='Usuario',
            field=models.CharField(max_length=15),
        ),
    ]
