# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investigador', '0001_initial'),
        ('Provincia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos_cientificos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Numero', models.IntegerField()),
                ('Estado', models.CharField(max_length=15)),
                ('Anio', models.IntegerField()),
                ('SSN', models.CharField(max_length=15)),
                ('Base_Datos', models.CharField(max_length=20)),
                ('Url', models.URLField()),
                ('Fecha_Publicacion', models.DateField()),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Provincia.provincia')),
            ],
        ),
    ]
