# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0009_auto_20171129_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='investigador',
        ),
    ]
