# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investigador', '0003_auto_20171129_1531'),
        ('Libro', '0010_remove_libro_investigador'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='investigador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador'),
        ),
    ]
