# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0013_auto_20171129_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Anio',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='investigador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador'),
        ),
    ]
