# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0019_auto_20171129_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos_cientificos',
            name='provincia',
        ),
        migrations.AlterField(
            model_name='articulos_cientificos',
            name='Nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articulos_cientificos',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
