# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0020_auto_20171201_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos_cientificos',
            name='Numero',
        ),
        migrations.AlterField(
            model_name='articulos_cientificos',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
