# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0002_auto_20171126_1613'),
        ('Articulos_Cientificos', '0024_auto_20171201_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos_cientificos',
            name='ciudad',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos_cientificos',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.pais'),
        ),
        migrations.AlterField(
            model_name='articulos_cientificos',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
