# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Revista', '0027_auto_20171203_1637'),
        ('Articulos_Cientificos', '0026_auto_20171201_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos_cientificos',
            name='revista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Revista.revista'),
        ),
        migrations.AlterField(
            model_name='articulos_cientificos',
            name='investigador',
            field=models.ManyToManyField(to='Investigador.investigador'),
        ),
    ]
