# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Lugar', models.CharField(max_length=20)),
                ('Fecha', models.DateField()),
            ],
        ),
    ]
