# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0002_auto_20171126_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universidad',
            name='zona',
        ),
    ]
